### ISSUE TITLE
define matplotlib config file for qttk

### ISSUE THREAD

**Issue by joe-wojniak** [conlan-scientific/qttk#27]
1. define matplotlib config file that loads when qttk is imported
2. matplotlib config file to have test mode where figs are not shown

**Comment by emican** [comment]
I was not sure how to use qttk_plot.py with a with subplots.  Have you tried adapting existing plots to use this new feature?

Tried something different on chaikin_money_flow.py (also checkout tests.sh), if any command line argument is passed, it will not plot.  It is assuming people who run a qttk module will want to see a plot by default.  Also found plt.show(block=False) can be used with a timer and plt.close(), but it would still create a plot.

**Comment by joe-wojniak** [comment]
the custom plots don't lend themselves well to a general function
(i.e. qttk_plot.py)

so, plot() can be called multiple times and it will generate separate
figures.  sometimes multiple time series will be combined into a
figure, so some experimentation is needed.

qttk_plot.py will not reproduce the customized plots, but can be used
to make new plots going forward.

some design patterns are shown in the examples folder- simple_plot.py

-Joe W.

On Sun, Feb 21, 2021 at 2:30 PM emican <notifications@github.com> wrote:
>
> I was not sure how to use qttk_plot.py with a with subplots. Have you tried adapting existing plots to use this new feature?
>
> Tried something different on chaikin_money_flow.py (also checkout tests.sh), if any command line argument is passed, it will not plot. It is assuming people who run a qttk module will want to see a plot by default. Also found plt.show(block=False) can be used with a timer and plt.close(), but it would still create a plot.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
-Joe Wojniak

CONFIDENTIALITY NOTICE: The contents of this email message and any
attachments are intended solely for the addressee(s) and may contain
confidential and/or privileged information and may be legally
protected from disclosure.

**Comment by joe-wojniak** [comment]
matplotlibrc doesn't need to be modified to implement the desired plotting functionality.
