### ISSUE TITLE
docstring reST experiments

### ISSUE THREAD

**Issue by emican** [conlan-scientific/qttk#30]
Experiment with reST docstrings formats that may enrich documentation.

**Comment by emican** [comment]
To preview: 
https://qttk.readthedocs.io/en/latest/index.html

The build was successful, but the docs are not as they appear locally.

environment.yml file probably has extra packages.  
Todo: try using the --from-history flag 'conda env export --from-history'

**Comment by chrisconlan** [comment]
Looking pretty good so far
