### ISSUE TITLE
TypeError raised when characterizing performance of r_squared.py

### ISSUE THREAD

**Issue by joe-wojniak** [conlan-scientific/qttk#31]
error raised: 
TypeError: 'numpy.float64' object is not callable when trying to characterize performance of r_squared.py

**Comment by emican** [comment]
It looks like the output of r_squared function is assigned to a variable r_squared on line 61.  So r_squared is a numpy.float64 after line 61.  After that change, a ValueError happened.  Changing the timed report to use test_df.close and test_df.open in place of close_price and predicited_values seems to have resolved the duplicate index entries ValueError.
```python
      function   n_values  t_milliseconds  values_per_ms
0   r_squared      10000           1.407      7106.1235
1   r_squared      17782           1.404     12663.5195
2   r_squared      31622           1.582     19984.4027
3   r_squared      56234           1.980     28403.9364
4   r_squared     100000           2.775     36039.8803
5   r_squared     177827           5.977     29754.0178
6   r_squared     316227          12.629     25039.2660
7   r_squared     562341          18.853     29827.3376
8   r_squared    1000000          30.203     33108.8772
9   r_squared    1778279          54.426     32673.1076
10  r_squared    3162277          83.522     37861.6371
11  r_squared    5623413         142.182     39550.9071
12  r_squared   10000000         246.983     40488.5725
13  r_squared   17782794         436.014     40784.9240
14  r_squared   31622776         772.378     40942.0968
15  r_squared   56234132        1386.633     40554.4456
16  r_squared  100000000        2448.194     40846.4290```

**Comment by joe-wojniak** [comment]
I keep getting the TypeError that numpy.float64 object is not
callable- this is what I tried:

with timed_report():
        tt = time_this(lambda *args, **kwargs: args[0].shape[0])
        for i in exp_range.iterator():
            tt(r_squared)(test_df.close[:i], test_df.open[:i])

On Sun, Feb 21, 2021 at 3:18 PM emican <notifications@github.com> wrote:
>
> It looks like the output of r_squared function is assigned to a variable r_squared on line 61. So r_squared is a numpy.float64 after line 61. After that change, a ValueError happened. Changing the timed report to use test_df.close and test_df.open in place of close_price and predicited_values seems to have resolved the duplicate index entries ValueError.
>
>       function   n_values  t_milliseconds  values_per_ms
> 0   r_squared      10000           1.407      7106.1235
> 1   r_squared      17782           1.404     12663.5195
> 2   r_squared      31622           1.582     19984.4027
> 3   r_squared      56234           1.980     28403.9364
> 4   r_squared     100000           2.775     36039.8803
> 5   r_squared     177827           5.977     29754.0178
> 6   r_squared     316227          12.629     25039.2660
> 7   r_squared     562341          18.853     29827.3376
> 8   r_squared    1000000          30.203     33108.8772
> 9   r_squared    1778279          54.426     32673.1076
> 10  r_squared    3162277          83.522     37861.6371
> 11  r_squared    5623413         142.182     39550.9071
> 12  r_squared   10000000         246.983     40488.5725
> 13  r_squared   17782794         436.014     40784.9240
> 14  r_squared   31622776         772.378     40942.0968
> 15  r_squared   56234132        1386.633     40554.4456
> 16  r_squared  100000000        2448.194     40846.4290```
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
-Joe Wojniak

CONFIDENTIALITY NOTICE: The contents of this email message and any
attachments are intended solely for the addressee(s) and may contain
confidential and/or privileged information and may be legally
protected from disclosure.

**Comment by joe-wojniak** [comment]
ok- i found the other fix: changing r_squared (the variable) to be r2, so that there is an unambiguous reference to the function r_squared()
